# Generated by harness-engineering v0.1.0 -- review and fill in before relying on it.
# One canonical entrypoint for this repository's own bootstrap/test/lint
# commands -- the same three commands declared verbatim in
# harness.config.json's verify block and in AGENTS.md's Verification
# section, so there is exactly one place any of them could drift.

.PHONY: bootstrap test lint check

bootstrap:
	./init.sh

test:
	node --test

lint:
	node --check scripts/action.mjs scripts/assess.mjs scripts/diff.mjs scripts/scaffold.mjs scripts/verify.mjs

check: test lint
