#!/usr/bin/env bash
set -euo pipefail

# This is a placeholder generated by harness-engineering's scaffold.
# Replace it with the real bootstrap sequence for this project -- installing
# dependencies, pulling required config, whatever a clean checkout needs
# before any command in AGENTS.md's Verification section can run. Until
# then, print what is missing instead of pretending setup succeeded.
echo "init.sh has not been filled in yet."
echo "Add the real setup steps here, then point harness.config.json's"
echo "verify.bootstrap at this script."
