import { TEMPLATE_WHITELIST, readTemplate } from './templates.mjs';
import { SUPPORTED_LANGS } from './i18n.mjs';

/**
 * Rule A -- an unreplaced placeholder marker.
 *
 * The colon is load-bearing, not decoration. templates/en/Makefile's own
 * lines 1-2 read "# Generated by harness-engineering's scaffold. Every
 * target below is a placeholder until the FILL lines are replaced": that is
 * prose ABOUT placeholders, and a bare /FILL/ would misjudge the whole file
 * as unfilled. Fix round 2, Finding 6: neither the Makefile template nor
 * init.sh actually contains a `FILL:` marker in either language (confirmed
 * with `grep -rl "FILL:" templates/`) -- the only six templates that do are
 * all markdown: AGENTS.md, evaluator-rubric.md, session-handoff.md, and the
 * three loop/*.md templates, where the marker is always written
 * `<!-- FILL: ... -->`. The task-1 brief's own "background facts" inherited
 * this error from the plan (Makefile turned up in a `grep -l FILL` search,
 * which matches the colon-less prose above too).
 */
const FILL_MARKER = /FILL:/;

/**
 * The shape scaffold.mjs's `stamp()` prepends to every non-foreign-JSON
 * template it writes (see PROVENANCE/`stamp()` in scripts/scaffold.mjs,
 * the source of truth this pattern mirrors rather than imports -- lib/
 * modules do not depend on the scripts/ entry points that use them).
 * Matched only by SHAPE, never a specific version number: hardcoding
 * e.g. "v0.1.0" would silently stop recognizing the stamp the next time
 * this project's own version number changes, quietly reopening Finding 1
 * below on every release.
 */
const PROVENANCE_TEXT = 'Generated by harness-engineering v\\S+ -- review and fill in before relying on it\\.';

/**
 * Fix round 2, Finding 1 (CRITICAL) -- Rule B as originally shipped compared
 * raw bytes, but `scaffold --apply` never writes a template byte-for-byte:
 * `stamp()` prepends a provenance line first. So a scaffolded-but-untouched
 * file was NEVER byte-identical to its template, and Rule B never fired for
 * it -- only the six templates that also carry a `FILL:` marker were still
 * caught, via Rule A. `clean-state-checklist.md` has no `FILL:` marker, so a
 * repository that ran `scaffold --apply` and touched nothing could pass
 * state.no-handoff/state.handoff-unfilled on that file alone. Reproduced
 * end to end (see task-1-report.md's fix-round-2 section) and fixed by
 * normalising the candidate side of the Rule B comparison before it runs:
 * strip the stamp's leading line via stripProvenanceStamp below (the shipped
 * template texts on the other side of the comparison never carry the stamp
 * in the first place, so stripping them too would be a no-op), mirroring
 * stamp()'s four branches in reverse --
 * markdown's `<!-- ... -->` line, a bare `# ...` comment line (Makefile),
 * that same comment line inserted as the SECOND line right after a
 * preserved shebang (init.sh), and a `"_generatedBy": "..."` field inserted
 * as the second line right after JSON's opening `{` (harness.config.json,
 * the one JSON template whose original formatting already matches
 * `JSON.stringify(_, null, 2)`).
 *
 * This closes the gap for eight of the ten templates that carry neither a
 * `FILL:` marker nor (before this fix) a working Rule B match: the three
 * `.md` ones (CLAUDE.md, PROGRESS.md, clean-state-checklist.md), Makefile,
 * init.sh, and harness.config.json, on top of the two FOREIGN_JSON
 * templates (.claude/settings.json, .devcontainer/devcontainer.json) that
 * were never stamped at all and so already round-tripped correctly.
 * `feature_list.json` and `feature_list.schema.json` remain unmatched even
 * after stripping their stamp line -- verified directly against the real
 * `stamp()`: `stamp()` always re-serializes JSON templates through
 * `JSON.parse` + `JSON.stringify(_, null, 2)`, and both of those two
 * templates are hand-formatted with compact inline objects that
 * `JSON.stringify(_, null, 2)` does not reproduce, so their *body* changes
 * shape on every scaffold regardless of the added stamp line -- a
 * pre-existing formatting mismatch, not a provenance-stamp problem, and out
 * of scope for this fix (no current or planned caller of `isFilledArtifact`
 * checks either file: state.mjs only ever passes session-handoff.md /
 * clean-state-checklist.md, both markdown).
 */
function stripProvenanceStamp(text) {
  let m = text.match(new RegExp(`^<!-- ${PROVENANCE_TEXT} -->\\n`));
  if (m) return text.slice(m[0].length);

  // init.sh: the stamp is inserted as the line right after the shebang, not
  // as the very first line, so the shebang must be checked (and kept) first.
  m = text.match(new RegExp(`^(#![^\\n]*\\n)# ${PROVENANCE_TEXT}\\n`));
  if (m) return m[1] + text.slice(m[0].length);

  m = text.match(new RegExp(`^# ${PROVENANCE_TEXT}\\n`));
  if (m) return text.slice(m[0].length);

  // JSON: the stamp is the "_generatedBy" field stamp() inserts as the
  // first key, which is textually the second line, right after "{".
  m = text.match(new RegExp(`^(\\{\\n)  "_generatedBy": "${PROVENANCE_TEXT}",\\n`));
  if (m) return m[1] + text.slice(m[0].length);

  return text;
}

/**
 * Rule B -- byte-identical (after stripping a leading provenance stamp, if
 * any -- see stripProvenanceStamp above) to something this project ships as
 * a template.
 *
 * Compared against EVERY shipped template's text rather than only the
 * same-named one: a repository that vendors our session-handoff.md under
 * some other name has still not written a handoff document, and matching by
 * content avoids a basename-mapping table that could drift out of sync with
 * TEMPLATE_WHITELIST (this codebase has been bitten by hand-synced parallel
 * lists four times -- see scan.mjs and environment.mjs's own comments).
 *
 * Built once, lazily: 16 templates x 2 languages is 32 reads, and only if
 * something actually asks.
 */
let shippedTexts = null;
function allShippedTemplateTexts() {
  if (shippedTexts === null) {
    shippedTexts = new Set();
    for (const name of TEMPLATE_WHITELIST) {
      for (const lang of SUPPORTED_LANGS) {
        // Guard, not decoration -- do not "clean this up" into a bare
        // shippedTexts.add(readTemplate(name, lang)). `assess` is
        // documented and tested (tests/packaging.test.mjs's "fully detached
        // plugin install" case) to run from installs that ship scripts/
        // without templates/ sitting next to it -- e.g. a script-only
        // Claude Code plugin cache copy. Before this module existed,
        // nothing on assess's read-only path ever imported templates.mjs,
        // so that install shape worked fine. readTemplate does a bare
        // readFileSync with no existence check, so an absent templates/
        // throws ENOENT here, and an uncaught exception here used to crash
        // the entire assess run over a directory that simply isn't there.
        //
        // Fix round 2, Finding 2: only ENOENT (the path doesn't exist) and
        // ENOTDIR (a path segment that should be a directory is a plain
        // file) are swallowed -- both mean "there is nothing to read here",
        // the exact case this guard exists for. Anything else (EACCES,
        // EMFILE, a corrupt filesystem, ...) is a transient or genuinely
        // exceptional failure that should surface loudly and fail the
        // `assess` run, not get silently absorbed into a permanently
        // weakened comparison set: shippedTexts is built once and memoized
        // for the process's whole lifetime, so swallowing a passing error
        // here would quietly and permanently degrade Rule B with no signal
        // that anything went wrong, for every check for the rest of the run.
        try {
          shippedTexts.add(readTemplate(name, lang));
        } catch (err) {
          if (err.code !== 'ENOENT' && err.code !== 'ENOTDIR') throw err;
          // Missing template directory/file: contributes nothing to Rule B.
        }
      }
    }
  }
  return shippedTexts;
}

/**
 * True when `rel` is a real, filled-in artefact rather than an unfilled
 * placeholder — a distinction the scorers used to be missing entirely: a
 * repository that only ever vendored this project's own unfilled templates
 * could score as if it had written real content.
 *
 * Deliberately NOT "exclude anything under templates/": that would
 * special-case one directory name and leave the general problem (a
 * placeholder counting as content) untouched. Both rules here are about the
 * file's CONTENT, so a repository keeping placeholders anywhere —
 * templates/, docs/, examples/, the root — is judged the same way.
 *
 * `ctx` is a scan.mjs scan context; only `ctx.read` is used.
 */
export function isFilledArtifact(ctx, rel) {
  const text = ctx.read(rel);
  if (text === null) return false;
  if (FILL_MARKER.test(text)) return false;
  if (allShippedTemplateTexts().has(stripProvenanceStamp(text))) return false;
  return true;
}
