#!/usr/bin/env node
/**
 * This is the second and last module in the project that writes files into
 * someone else's repository (the first is Task 18's verify --run, but that
 * one only ever writes under `.harness/`). scaffold.mjs writes real,
 * top-level files a repository owner already has opinions about --
 * AGENTS.md, Makefile, .claude/settings.json. Its headline promise is not
 * "generates good content", it is:
 *
 *   An already-existing file is never overwritten, under any circumstance.
 *
 * That single guarantee is why a stranger can run this with --apply at all.
 * Break it once and the tool is unusable against any real checkout. It is
 * therefore treated with the same weight as safety.mjs's dangerous-command
 * blocklist: every path this module can ever write is drawn from
 * `TEMPLATE_WHITELIST` (templates.mjs, Task 19), re-validated at the one
 * point every write actually happens (see `assertWhitelisted` and
 * `readTemplate`'s own internal check -- two independent layers, not one),
 * and no write is ever attempted at all unless `--apply` was explicitly
 * passed (see the early return in `runScaffold`, before a single `mkdirSync`
 * or `writeFileSync` call exists on any code path).
 *
 * Data flow: rubric.mjs's GAPS (Task 7, `templates` field) -> either
 * runAssess's report (Task 15, default path) or a user-supplied --only
 * (escape hatch, see the B1 note below) -> templates.mjs's readTemplate
 * (Task 19) -> a target path inside the caller's repository.
 */
import {
  existsSync, mkdirSync, writeFileSync, chmodSync, readFileSync, realpathSync,
} from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseCli, resolveRepoPath, CliError } from './lib/cli.mjs';
import { assertLang, t } from './lib/i18n.mjs';
import { createScanContext } from './lib/scan.mjs';
import { loadConfig } from './lib/config.mjs';
import { TEMPLATE_WHITELIST, readTemplate } from './lib/templates.mjs';
import { GAPS, SUBSYSTEMS, gapById, gapsFor } from './lib/rubric.mjs';
import { runAssess } from './assess.mjs';
import { allGaps } from './lib/report.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));

// Same pattern, same fallback, as assess.mjs's toolVersion() -- copied
// rather than imported, since it's script-entry-point-level plumbing, not
// library code that belongs under scripts/lib/ (see isMainModule's own
// comment below for the same reasoning applied to a different function).
function toolVersion() {
  try {
    return JSON.parse(readFileSync(join(HERE, '..', '.claude-plugin', 'plugin.json'), 'utf8')).version;
  } catch { return '0.0.0-dev'; }
}

const PROVENANCE = 'Generated by harness-engineering';

/**
 * Brief section B2 (measured by the controller against the plan's own
 * `stamp()` skeleton before dispatch): the plan injects `_generatedBy` into
 * *every* `.json` template unconditionally. Two of the sixteen whitelisted
 * templates are not this project's own format at all --
 * `.claude/settings.json` is Claude Code's own config schema, and
 * `.devcontainer/devcontainer.json` is the Dev Containers spec -- and Task
 * 19 already made and shipped the opposite call for the same class of
 * problem: harness.config.json (this project's own format) got a
 * `_comment` field, but `.claude/settings.json` and `devcontainer.json`
 * were deliberately left untouched (task-19-report.md). Injecting an
 * unrecognized top-level key into someone else's schema risks nothing more
 * than a lint warning in the best case and a rejected config in the worst,
 * and there is no upside: the tool that actually reads either file has no
 * use for `_generatedBy`. Keeping this decision consistent with Task 19
 * means these two never get stamped at all -- provenance for them is
 * carried by the `Plan` entry / CLI output instead (see renderScaffold
 * below), never inside the file.
 */
const FOREIGN_JSON = new Set(['.claude/settings.json', '.devcontainer/devcontainer.json']);

/**
 * Insert a provenance marker in a way that keeps each format valid --
 * spec rule 4. `FOREIGN_JSON` (B2, above) is checked first and returns the
 * template byte-for-byte unmodified; every other extension gets a
 * format-appropriate comment (Markdown `<!-- -->`, `#` for shell/Makefile),
 * and JSON gets a top-level `_generatedBy` field instead of a comment,
 * since JSON has no comment syntax.
 */
export function stamp(name, content, version) {
  if (FOREIGN_JSON.has(name)) return content;
  const line = `${PROVENANCE} v${version} -- review and fill in before relying on it.`;
  if (name.endsWith('.json')) {
    const parsed = JSON.parse(content);
    return `${JSON.stringify({ _generatedBy: line, ...parsed }, null, 2)}\n`;
  }
  if (name.endsWith('.md')) return `<!-- ${line} -->\n${content}`;
  if (name === 'init.sh') {
    const [shebang, ...rest] = content.split('\n');
    return [shebang, `# ${line}`, ...rest].join('\n');
  }
  return `# ${line}\n${content}`; // Makefile and anything else shell-comment-style
}

/**
 * Defense-in-depth, deliberately redundant with templates.mjs's own
 * `templatePath`/`readTemplate` (which already throw `Not a whitelisted
 * template: ...` for any name outside `TEMPLATE_WHITELIST`, and which this
 * module cannot modify). Every write in this file goes through
 * `readTemplate` regardless, so that check alone already makes an
 * off-whitelist write structurally unreachable through any public
 * `runScaffold` call -- see task-20-report.md's mutation-testing section
 * for what was actually verified about that (removing *this* function
 * alone, without also touching templates.mjs, does not by itself let
 * anything through, precisely because that second layer exists). This
 * function exists anyway, checked earlier and independently of
 * `readTemplate`, for the same reason safety.mjs treats its hard rules as
 * non-negotiable rather than trusting a single check: a boundary this load-
 * bearing should not have exactly one line standing between it and a
 * regression.
 */
export function assertWhitelisted(name) {
  if (!TEMPLATE_WHITELIST.includes(name)) {
    throw new Error(`Refusing to write a non-whitelisted path: ${name}`);
  }
}

/**
 * Resolve `--only` tokens to gap ids. Brief section B1 (Critical, the
 * plan's own prose and its own test contradict each other -- see
 * task-20-report.md for the full writeup): this project chose *direct-
 * select* semantics over *filter* semantics. `--only` is an escape hatch
 * that names gap ids / subsystem ids straight out of rubric.mjs's GAPS,
 * completely independent of whatever `runAssess` would or would not report
 * for this repository -- it does not even run assess. Two things follow
 * from that, both deliberate: (1) the plan's own test 3 (mid-repo,
 * `only: ['instructions.missing']`, a gap mid-repo does NOT actually have,
 * since it already has an AGENTS.md) only passes under this semantics --
 * under filter semantics it would select an empty set and write nothing;
 * (2) `--only` keeps working even against a repository whose `runAssess`
 * would throw or behave oddly for unrelated reasons, which a pure filter
 * could never offer.
 *
 * Each token may be a comma-separated list (`--only a,b`) as well as a
 * repeated flag (`--only a --only b`); both funnel through the same
 * per-token resolution below.
 */
function resolveOnly(tokens) {
  const ids = [];
  const seen = new Set();
  const add = (id) => { if (!seen.has(id)) { seen.add(id); ids.push(id); } };
  for (const raw of tokens) {
    for (const token of raw.split(',').map((s) => s.trim()).filter(Boolean)) {
      if (GAPS.some((g) => g.id === token)) { add(token); continue; }
      if (SUBSYSTEMS.includes(token)) {
        for (const g of gapsFor(token)) if (g.scaffoldable) add(g.id);
        continue;
      }
      // A usage error (bad flag value), not an internal failure -- same
      // exit-code family as assess.mjs's --min-level / verify.mjs's
      // --timeout: CliError, exit 2, caught uniformly by main() below.
      throw new CliError(
        `Unknown gap id or subsystem: '${token}'. Use a gap id (e.g. `
        + `state.no-progress) or a subsystem id (${SUBSYSTEMS.join(', ')}).`,
      );
    }
  }
  return ids;
}

/**
 * Which gap ids to scaffold, and in what order. Default path (rule 5's
 * first clause, `only` unset): every `scaffoldable` gap `runAssess` actually
 * found for this repository, ROI descending.
 *
 * `allGaps`, not the subset `renderMarkdown` prints. Writing a file is a
 * behavioural decision, so it acts on every failing check -- a gap that is
 * merely not worth SHOWING beside its precondition is still a gap whose
 * template the repository is missing. This matters concretely:
 * loop.no-maker-checker is suppressed beside loop.none but is the only
 * claimant of `evaluator-rubric.md`, so reading the printed subset here
 * would silently stop scaffold offering it to exactly the repositories with
 * no loop at all. `--only` path: see `resolveOnly` above.
 */
function selectGapIds({ only, repoPath, lang, configPath, now }) {
  if (only && only.length > 0) return resolveOnly(only);
  const report = runAssess({ repoPath, lang, configPath, now });
  return allGaps(report).filter((g) => g.scaffoldable).map((g) => g.id);
}

/**
 * Where a template should land can itself already be occupied -- not just
 * by the real target (that's the propose/create branch below), but by a
 * PRIOR `.harness-proposed` from an earlier scaffold run the user hasn't
 * reviewed yet. Brief section E1: the never-overwrite guarantee draws no
 * exception for this project's own previously-generated proposals -- the
 * user may be mid-review of it, may have annotated it by hand. So this
 * escalates to `.harness-proposed-2`, `-3`, ... instead of silently
 * clobbering whatever is already sitting at the first candidate path.
 * Bounded (not an unbounded loop) purely so a pathological repeat-invocation
 * fails loudly with a clear message instead of spinning forever.
 */
const MAX_PROPOSE_ATTEMPTS = 1000;
function nextAvailablePath(basePath) {
  if (!existsSync(basePath)) return basePath;
  for (let i = 2; i <= MAX_PROPOSE_ATTEMPTS; i++) {
    const candidate = `${basePath}-${i}`;
    if (!existsSync(candidate)) return candidate;
  }
  throw new Error(
    `Too many existing '${basePath}*' proposals in this repository -- `
    + 'review and clean some up before scaffolding again.',
  );
}

/**
 * Build the write plan: exactly one entry per DISTINCT target template.
 * Brief section B3 (Important, measured by the controller against bad-repo
 * before dispatch): `loop/maker-checker-loop.md` is listed under BOTH
 * `loop.no-maker-checker` and `loop.none`'s `templates`. Writing it once per
 * claiming gap would both duplicate `written` and -- because the second
 * write would find the first write's own output already sitting there --
 * degrade into writing `loop/maker-checker-loop.md` AND
 * `loop/maker-checker-loop.md.harness-proposed` in the very same run,
 * which is exactly the confusing double-artifact the brief calls out.
 *
 * Dedup is by target template name, in `gapIds` order (already
 * ROI-descending for the default path -- see `selectGapIds`): the first gap
 * to claim a given template keeps that `Plan` entry's `gapId`; every later
 * gap referencing the same template is treated as already satisfied by the
 * earlier one's proposal and contributes no second entry at all. This is
 * explainable, not arbitrary: whichever gap scaffold would have prioritized
 * fixing first is also the gap credited with the fix.
 *
 * `existsSync`/`nextAvailablePath` here are read-only filesystem probes --
 * safe to run even during a dry-run planning pass (rule 1 only forbids
 * *writes*), which is what lets `planned` show the caller an accurate
 * preview (including the exact `-2`/`-3` escalation a real `--apply` would
 * produce) without this function ever creating or modifying anything.
 */
function buildPlan(gapIds, repoPath) {
  const claimed = new Set();
  const plan = [];
  for (const gapId of gapIds) {
    for (const name of gapById(gapId).templates) {
      if (claimed.has(name)) continue;
      claimed.add(name);
      assertWhitelisted(name);
      const absTarget = join(repoPath, ...name.split('/'));
      if (!existsSync(absTarget)) {
        plan.push({ template: name, target: name, action: 'create', gapId });
        continue;
      }
      const absProposed = nextAvailablePath(`${absTarget}.harness-proposed`);
      const target = absProposed.slice(repoPath.length + 1).split(/[\\/]/).join('/');
      plan.push({ template: name, target, action: 'propose', gapId });
    }
  }
  return plan;
}

/**
 * Pure orchestration modulo the two documented exceptions any Task-1x
 * module in this project carries: `now` is caller-supplied (no
 * `Date.now()`/`new Date()` in this function, matching runAssess/runVerify's
 * own contract), and `--apply` performs real filesystem I/O.
 *
 * Rule 1 (dry-run writes nothing): the ONLY `return` in the entire function
 * that precedes any `mkdirSync`/`writeFileSync`/`chmodSync` call is the
 * `!apply` branch immediately below -- there is no code path that reaches a
 * filesystem mutation without `apply === true` first being checked.
 */
export function runScaffold({
  repoPath, lang, only, apply = false, configPath, now,
}) {
  assertLang(lang);
  const gapIds = selectGapIds({
    only, repoPath, lang, configPath, now,
  });
  const planned = buildPlan(gapIds, repoPath);

  if (!apply) return { planned, written: [] };

  const written = [];
  const version = toolVersion();
  for (const plan of planned) {
    const absTarget = join(repoPath, ...plan.target.split('/'));
    try {
      mkdirSync(dirname(absTarget), { recursive: true });
      const raw = readTemplate(plan.template, lang); // re-validates whitelist + lang -- see assertWhitelisted's comment
      writeFileSync(absTarget, stamp(plan.template, raw, version));
      // Brief section E2: only a freshly CREATED init.sh gets the
      // executable bit (matching the plan's own step-3 instruction,
      // `init.sh` written -> `chmodSync(0o755)`). A *proposed* alternative
      // (`init.sh.harness-proposed`) deliberately does NOT -- making an
      // unreviewed proposal executable nudges towards running content
      // nobody has read yet, which is exactly the failure mode the whole
      // propose-instead-of-overwrite design exists to prevent. The safer
      // reading of "should the proposed copy also get +x" is no.
      if (plan.template === 'init.sh' && plan.action === 'create') chmodSync(absTarget, 0o755);
      written.push(plan.target);
    } catch (err) {
      // Brief section E3: a write failing partway through --apply (full
      // disk, read-only mount, permission denied) must not leave this
      // function pretending nothing happened, and must not silently bubble
      // as an uncaught exception either (main()'s top-level catch-all would
      // then report it as an *unexpected internal* failure, exit 3 --
      // wrong, since a full disk is an ordinary, anticipatable environment
      // condition, not a bug in this tool). Deliberately NO rollback of
      // files already written: undoing them would itself be a destructive
      // delete, attempted under exactly the conditions (full disk, denied
      // permission) most likely to make the delete ALSO fail, and it would
      // erase real files the caller may already be depending on moments
      // after they were written. `written` instead reflects the literal,
      // honest state of the filesystem at the point of failure -- no more,
      // no less -- and `failure` names exactly which entry stopped the run
      // and why, so a caller can never mistake a partial run for a
      // complete, successful one.
      return {
        planned,
        written,
        failure: {
          template: plan.template, target: plan.target, gapId: plan.gapId, message: err.message,
        },
      };
    }
  }
  return { planned, written };
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

function renderScaffold(result, lang, apply) {
  const lines = [`# ${t('scaffold.title', lang)}`, ''];
  lines.push(t(apply ? 'scaffold.mode.apply' : 'scaffold.mode.dryRun', lang), '');
  if (result.planned.length === 0) {
    lines.push(t('scaffold.noGaps', lang), '');
    return lines.join('\n');
  }
  lines.push(`## ${t('scaffold.planHeading', lang)}`, '');
  lines.push(`| ${t('scaffold.col.action', lang)} | ${t('scaffold.col.target', lang)} | ${t('scaffold.col.gap', lang)} |`);
  lines.push('| --- | --- | --- |');
  for (const p of result.planned) {
    const actionLabel = t(`scaffold.action.${p.action}`, lang);
    lines.push(`| ${actionLabel} | \`${p.target}\` | ${p.gapId} |`);
  }
  lines.push('');
  if (!apply) {
    lines.push(t('scaffold.applyHint', lang), '');
  } else if (result.failure) {
    lines.push(t('scaffold.failure', lang, { target: result.failure.target, message: result.failure.message }), '');
    if (result.written.length > 0) {
      lines.push(t('scaffold.writtenSoFar', lang, { list: result.written.join(', ') }), '');
    }
  }
  return lines.join('\n');
}

function main(argv) {
  const { values, positionals } = parseCli(argv, {
    options: {
      lang: { type: 'string' },
      only: { type: 'string', multiple: true },
      apply: { type: 'boolean', default: false },
      config: { type: 'string' },
    },
    allowPositional: true,
  });
  const repoPath = resolveRepoPath(positionals, process.cwd());
  const ctx = createScanContext(repoPath);
  const lang = assertLang(values.lang ?? loadConfig(ctx, { configPath: values.config }).lang);

  const result = runScaffold({
    repoPath, lang, only: values.only, apply: values.apply, configPath: values.config, now: new Date(),
  });

  process.stdout.write(`${renderScaffold(result, lang, values.apply)}\n`);

  // Spec (task-20-brief-raw.md Interfaces): dry-run always exits 0;
  // an inability to write (or a missing template) exits 1. Mirrors
  // assess.mjs's --min-level / verify.mjs's `report.passed` pattern of
  // returning the gate result rather than throwing it -- a write failure
  // here is an ordinary, expected environment condition (disk full,
  // read-only mount), not the "something in this tool itself broke"
  // case that exit 3 is reserved for.
  return result.failure ? 1 : 0;
}

// Identical to assess.mjs's / verify.mjs's own isMainModule -- see either
// one's full comment for the complete reasoning (symlinked /tmp on macOS,
// spaces/unicode in the path, why pathToFileURL alone still isn't enough).
// Copied verbatim rather than imported: script-entry-point logic, not
// library code that belongs under scripts/lib/.
function isMainModule() {
  if (process.argv[1] === undefined) return false;
  try {
    return fileURLToPath(import.meta.url) === realpathSync(process.argv[1]);
  } catch {
    return false;
  }
}

if (isMainModule()) {
  try {
    process.exit(main(process.argv.slice(2)));
  } catch (err) {
    if (err instanceof CliError) {
      process.stderr.write(`${err.message}\n`);
      process.exit(err.exitCode);
    }
    process.stderr.write(`${err.stack ?? err.message}\n`);
    process.exit(3);
  }
}
